export const API_BASE_URL='http://api.nytimes.com/svc/';
export const API_KEY='qWO5J56rRa4sdwmDlndp4wv5EEAZecAR';
export const Days = ['1', '7', '30'];
export const Categories = [
    'Arts',
    'Automobiles',
    'Autos',
    'Blogs',
    'Books',
    'Booming',
    'Business',
    'Business Day',
    'Corrections',
    'Crosswords & Games',
    'Crosswords/Games',
    'Dining & Wine',
    'Dining and Wine',
    'Editors Notes',
    'Education',
    'Fashion & Style',
    'Food',
    'Front Page',
    'Giving',
    'Global Home',
    'Great Homes & Destinations',
    'Great Homes and Destinations',
    'Health',
    'Home & Garden',
    'Home and Garden',
    'International Home',
    'Job Market',
    'Learning',
    'Magazine',
    'Movies',
];