export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_STARTED = 'FETCH_ARTICLES_STARTED';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';
export const LOAD_MORE = 'LOAD_MORE';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const TOGGLE_POP_UP_MENU = 'TOGGLE_POP_UP_MENU';
export const TOGGLE_FILTERS_OPTIONS = 'TOGGLE_FILTERS_OPTIONS';