export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_STARTED = 'FETCH_STARTED';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';